export default {
  homePageGallery: document.querySelector('.js-main-page'),
  formInput: document.querySelector('.formSearch'),
  input: document.querySelector('.inputSearch'),
  divPagination: document.querySelector('.pagination'),
  prevBtn: document.querySelector('#prev'),
  nextBtn: document.querySelector('#next'),
  numberPage: document.querySelector('.numberPage'),

  divPaginationLib: document.querySelector('.paginationLib'),
  prevBtnLib: document.querySelector('#prevLib'),
  nextBtnLib: document.querySelector('#nextLib'),
  numberPageLib: document.querySelector('.numberPageLib'),

  errorDiv: document.querySelector('.errorPage'),
  errorLib: document.querySelector('.errorPageLib'),
  navHome: document.querySelector('.js-link-to-home'),
  navLibrary: document.querySelector('.js-link-to-myLibrary'),
  mainPage: document.querySelector('.main-page'),
  mainLibrary: document.querySelector('.library'),
  mainDetailsPage: document.querySelector('.details-page'),
  btnToWatched: document.querySelector('button[data-target="toWatched"]'),
  btnToQueue: document.querySelector('button[data-target="toQueue"]'),
  logo: document.querySelector('.js-logo-block'),
  divButtons: document.querySelector('#buttonsMyFilm'),
  btnUp: document.querySelector('.footer-btnUp'),

  libraryGallery: document.querySelector('.library-list'),
  buttWatch: document.querySelector('.watch'),
  buttQue: document.querySelector('.queue'),
  imgDetailsWrapper: document.querySelector('.img-wrapper'),
  infoDetailsBox: document.querySelector('.info-box'),
  spinner: document.querySelector('.loader'),
  errorPage: document.querySelector('.error-page'),

  player: document.querySelector('#trailer'),
};
